### ISSUE TITLE
"getdadjoke isnt a function"

### ISSUE THREAD

**Issue by SmugTheKiler** [Drxckzyz/get-dadjoke#1]
saying its not a function when I do

const joke = await dadjoke()

and before that I do do const dadjoke = require('get-dadjoke')

**Comment by Drxckzyz** [comment]
Thats because your calling it wrong, "dadjoke" is not a function its a const that contains multiple function so you would have to do 
 `await dadjoke.getDadjoke()`

**Comment by Drxckzyz** [comment]
Also you seem to be using the `get-dadjoke` package, which was renamed to `random-jokes` and changed heavily

**Comment by SmugTheKiler** [comment]
ok, thanks
